spring:
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate.dialect.storage_engine: innodb
  r2dbc:
    url: r2dbcs:mysql://127.0.0.1:3306/vehicle
    username: root
    password: root
  flyway:
    url: jdbc:mysql://localhost:3306/vehicle
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1.4
    locations: classpath:db/migration