spring:
  application:
    name: vdn
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate.dialect.storage_engine: innodb
  r2dbc:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  flyway:
    url: ${FLYWAY_URL}
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1.4
    locations: classpath:db/migration
aws:
  key: ${ACCESS_KEY}
  secret: ${ACCESS_SECRET}
  sns:
    arn: ${SNS_TOPIC_ARN}